# Generated by Django 3.1.2 on 2022-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0002_agents_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
