# Generated by Django 3.1.2 on 2022-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0004_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='maelezo',
            field=models.TextField(max_length=1000000),
        ),
    ]
