# Generated by Django 3.1.2 on 2022-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0005_auto_20220404_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=100)),
                ('maoni', models.TextField(max_length=100000)),
            ],
        ),
    ]
