# Generated by Django 3.1.2 on 2022-04-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picha', models.ImageField(upload_to='')),
                ('maelezo', models.TextField(max_length=1000000)),
            ],
        ),
    ]
