# Generated by Django 3.1.2 on 2022-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyumba', '0009_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
